from pathlib import Path

ROOT_DIR = Path(__file__).parent

IMAGES_PATH = ROOT_DIR / 'images'
ICON_PATH = IMAGES_PATH / 'icon.png'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUN_WIDTH = 500

# Colors
PRIMARY_COLOR = "#1e81b0"
DARKER_PRIMARY_COLOR = "#16658a"
DARKEST_PRIMARY_COLOR = "#115270"
